name = "crud-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_name = "crud.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

[durable_objects]
bindings = [{name = "CRUD", class_name = "CRUD"}]

[[migrations]]
tag = "v1"
new_classes = ["CRUD"]
